data_params:
  raw_text_filetype: .txt
directories:
  data: ./data
  raw_text: ./data/raw_text
embedding_params: {}
parser_params:
  delimiter_index: 3
  delimiter_token: "\u3002"
  pad_index: 0
  pad_token: PAD
  start_index: 2
  start_token: START
  unknown_index: 1
  unknown_token: UNKNOWN
print_params:
  break_halfline: "\t\t=========================================="
  break_line: ==========================================================
  break_subline: "\t=================================================="
