BREAK_HALFLINE: "\t\t=============\n"
BREAK_LINE: '=====================

  '
BREAK_SUBLINE: "\t=================\n"
data_params:
  paired_data_filetype: .csv
  source_corpus_filetype: .txt
  synthesized_data_prefix: syn
database_params:
  length_prefix: l
  sort_form_prefix: stf
  sort_tag_prefix: stt
  syntactic_tag_prefix: st
  token_prefix: t
  unique_form_prefix: uf
  unique_syntactic_tag_prefix: ust
  unique_token_prefix: ut
directories:
  data: /home/yukina-/Projects/rewrite/data
  databases: /home/yukina-/Projects/rewrite/data/databases
  languages: /home/yukina-/Projects/rewrite/data/languages
  rules: /home/yukina-/Projects/rewrite/data/rules
  sorted_tag_databases: /home/yukina-/Projects/rewrite/data/sorted_tag_databases
  source_corpora: /home/yukina-/Projects/rewrite/data/source_corpora
  synthesized_data: data/synthesized
language_params:
  delimiter: "\u3002"
  index_node: in.pkl
  node_count: nc.pkl
  node_index: ni.pkl
  pad_index: 0
  pad_token: '*'
  start_index: 2
  start_token: START
  stop_index: 3
  stop_token: STOP
  syntactic_tag_prefix: st
  token_prefix: t
  unknown_index: 1
  unknown_token: UNK
parser_params:
  delimiter: "\u3002"
  dictionary_dir: /usr/local/lib/mecab/dic/mecab-ipadic-neologd
  parse_indices:
  - 0
  - 1
  - 4
  - 5
  - 6
  parse_labels:
  - part-of-speech
  - part-of-speech sub-category
  - inflection
  - conjugation
  - root form
rule_params:
  class: Rule Class
  mapping_inserted: Inserted
  mapping_modified: Modified
  mapping_preserved: Preserved
  number: '#'
  subclass: Rule Subclass
  syntactic_tag_mask: Requisite Syntactic Tags
  syntactic_tags: Mecab Output
  template_correct_phrase: Template Correct Phrase
  template_error_phrase: Template Error Phrase
seed: 23
=======
BREAK_LINE: '=====================

  '
data_params: {source_corpus_filetype: .txt}
directories: {data: /home/yukina/Projects/aitutor/japanese_gec/data, languages: /home/yukina/Projects/aitutor/japanese_gec/data/languages,
  source_corpora: /home/yukina/Projects/aitutor/japanese_gec/data/source_corpora}
language_params: {delimiter: "\u3002", index_node: in.pkl, node_count: nc.pkl, node_index: ni.pkl,
  pad_index: 0, pad_token: '*', start_index: 2, start_token: START, stop_index: 3,
  stop_token: STOP, syntactic_tag_prefix: st, token_prefix: t, unknown_index: 1, unknown_token: UNK}
parser_params:
  delimiter: "\u3002"
  parse_indices: [0, 1, 4, 5, 6]
  parse_labels: [Part-of-speech, Part-of-speech Sub-category, Inflection, Conjugation,
    Root Form]
